# Generated by Django 2.1.2 on 2018-10-12 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chismes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chisme',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
